# Generated by Django 5.2 on 2025-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0002_alter_vitals_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
